# JavaScript 错误处理

> 原文:[https://www . tutorial Republic . com/JavaScript-tutorial/JavaScript-error-handling . PHP](https://www.tutorialrepublic.com/javascript-tutorial/javascript-error-handling.php)

在本教程中，你将学习如何在 JavaScript 中优雅地处理错误。

## 处理错误

有时，您的 JavaScript 代码没有像预期的那样顺利运行，从而导致错误。可能导致错误的原因有很多，例如:

*   网络连接有问题
*   用户可能在表单域中输入了无效值
*   引用不存在的对象或函数
*   发送到 web 服务器或从 web 服务器接收的数据不正确
*   应用程序需要访问的服务可能暂时不可用

这些类型的错误被称为运行时错误，因为它们发生在脚本运行时。专业应用程序必须有能力优雅地处理这种运行时错误。通常这意味着更清楚、更准确地通知用户问题。

## 尝试...catch 语句

JavaScript 提供了`try-catch`语句来捕获运行时错误，并优雅地处理它们。

任何可能抛出错误的代码都应该放在语句的`try`块中，处理错误的代码放在`catch`块中，如下所示:

try {
    *// Code that may cause an error*
} catch(error) {
    *// Action to be performed when an error occurs*
}

如果在`try`块的任何一点出现错误，代码执行会立即从`try`块转移到`catch`块。如果`try`块中没有错误发生，`catch`块将被忽略，程序将在`try-catch`语句后继续执行。

下面的例子演示了`try-catch`语句实际上是如何工作的:

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=try-catch-statement "Try this code using online Editor")

```
try {
    var greet = "Hi, there!";
    document.write(greet);

    // Trying to access a non-existent variable
    document.write(welcome);

    // If error occurred following line won't execute
    alert("All statements are executed successfully.");
} catch(error) {
    // Handle the error
  alert("Caught error: " + error.message);
}

// Continue execution
document.write("<p>Hello World!</p>");
```

上述脚本将生成一个错误，显示在一个警告对话框中，而不是打印到浏览器控制台。此外，即使出现错误，程序也不会突然停止。

另外，请注意,`catch`关键字后面是括号中的标识符。这个标识符就像一个函数参数。当错误发生时，JavaScript 解释器会生成一个包含错误详细信息的对象。然后这个错误对象作为参数传递给`catch`进行处理。

 ***提示:**`try-catch`语句是一种异常处理机制。异常是一种信号，表示在程序执行过程中发生了某种异常情况或错误。术语“异常”和“错误”经常互换使用。*  ** * *

## 尝试...捕捉...最终声明

`try-catch`语句也可以有一个`finally`子句。无论`try`块中是否出现错误，在`finally`块中的代码总是会执行。

以下示例将始终显示完成代码执行所用的总时间。

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=try-catch-finally-statement "Try this code using online Editor")

```
// Assigning the value returned by the prompt dialog box to a variable
var num = prompt("Enter a positive integer between 0 to 100");

// Storing the time when execution start
var start = Date.now();

try {
    if(num > 0 && num <= 100) {
        alert(Math.pow(num, num)); // the base to the exponent power
    } else {
        throw new Error("An invalid value is entered!");
    }
} catch(e) {
    alert(e.message);
} finally {
    // Displaying the time taken to execute the code
    alert("Execution took: " + (Date.now() - start) + "ms");
}
```

* * *

## 投掷错误

到目前为止，我们已经看到了 JavaScript 解析器在错误发生时自动抛出的错误。然而，也可以通过使用`throw`语句手动抛出一个错误。

`throw`语句的一般形式(或语法)是:`throw *expression*;`

`*expression*`可以是任何数据类型的对象或值。然而，最好使用对象，最好是具有`name`和`message`属性的对象。JavaScript 内置的`Error()`构造函数提供了一种创建错误对象的便捷方式。让我们看一些例子:

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=throw-statement "Try this code using online Editor")

```
throw 123;
throw "Missing values!";
throw true;
throw { name: "InvalidParameter", message: "Parameter is not a number!" };
throw new Error("Something went wrong!");
```

 ***注意:**如果使用的是 JavaScript 内置错误构造函数(如`Error()`、`TypeError()`等)。)来创建错误对象，那么`name`属性与构造函数的名称相同，`message`等于传递给构造函数的参数。*  *现在我们要创建一个函数`squareRoot()`来寻找一个数的平方根。这可以简单地通过使用 JavaScript 内置函数`Math.sqrt()`来完成，但是这里的问题是，对于负数，它返回`NaN`，而没有提供任何出错的提示。

如果提供了负数，我们将通过抛出一个自定义错误来解决这个问题。

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=throwing-an-error "Try this code using online Editor")

```
function squareRoot(number) {
    // Throw error if number is negative
    if(number < 0) {
        throw new Error("Sorry, can't calculate square root of a negative number.");
    } else {
        return Math.sqrt(number);
    }
}

try {
    squareRoot(16);
    squareRoot(625);
    squareRoot(-9);
    squareRoot(100);

    // If error is thrown following line won't execute
    alert("All calculations are performed successfully.");
} catch(e) {
    // Handle the error
    alert(e.message);
}
```

 ***提示:**理论上可以用虚数`*i*`计算负数的平方根，其中`*i*<sup>2</sup> = -1`。因此`-4`的平方根是`2i`,`-9`的平方根是`3i`，以此类推。但是 JavaScript 不支持虚数。*  ** * *

## 错误类型

`Error`对象是所有错误的基本类型，它有两个主要属性——一个是指定错误的*类型的`name`属性，另一个是保存更详细描述错误的消息的`message`属性。任何抛出的错误都将是`Error`对象的一个实例。*

在 JavaScript 程序的执行过程中可能会出现几种不同类型的错误，例如`RangeError`、`ReferenceError`、`SyntaxError`、`TypeError`和`URIError`。

以下部分更详细地描述了每种错误类型:

## 范围误差

当您使用超出允许值范围的数字时，会抛出一个`RangeError`。比如创建一个长度为负的数组会抛出`RangeError`。

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=range-error "Try this code using online Editor")

```
var num = 12.735;
num.toFixed(200); // throws a range error (allowable range from 0 to 100)

var array = new Array(-1); // throws a range error
```

## 参考错误

当你试图引用或访问一个不存在的变量或对象时，通常会抛出一个`ReferenceError`。下面的例子展示了`ReferenceError`是如何发生的。

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=reference-error "Try this code using online Editor")

```
var firstName = "Harry";
console.log(firstname); // throws a reference error (variable names are case-sensitive)

undefinedObj.getValues(); // throws a reference error

nonexistentArray.length; // throws a reference error
```

## 句法误差

如果 JavaScript 代码中有任何语法问题，就会在运行时抛出一个`SyntaxError`。例如，如果缺少右括号，则循环结构不正确，等等。

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=syntax-error "Try this code using online Editor")

```
var array = ["a", "b", "c"];
document.write(array.slice(2); // throws a syntax error (missing bracket)

alert("Hello World!'); // throws a syntax error (quote mismatch)
```

## TypeError

当一个值不是预期的类型时，抛出一个`TypeError`。比如对 number 调用 string 方法，对 string 调用 array 方法等等。

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=type-error "Try this code using online Editor")

```
var num = 123;
num.toLowerCase(); /* throws a type error (since toLowerCase() is a string method, a number can't be converted to lowercase) */

var greet = "Hello World!"
greet.join() // throws a type error (since join() is an array method)
```

## URIError

当你指定了一个无效的 URI ( *代表*统一资源标识符)给 URI 相关的函数，比如`encodeURI()`或者`decodeURI()`，就会抛出一个`URIError`，如下所示:

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=uri-error "Try this code using online Editor")

```
var a = "%E6%A2%B";
decodeURI(a);  // throws a URI error

var b = "\uD800";
encodeURI(b);   // throws a URI error
```

 ***注意:**还有一种错误类型`EvalError`，通过`eval()`函数在代码执行过程中出现错误时抛出。但是，JavaScript 不再抛出这个错误，然而这个对象仍然保持向后兼容。*  *特定的错误类型也可以使用各自的构造函数和`throw`语句手动抛出，例如，要抛出一个`TypeError`可以使用`TypeError()`构造函数，如下所示:

#### 例子

[Try this code »](../codelab.php?topic=javascript&file=throwing-specific-error-type "Try this code using online Editor")

```
var num = prompt("Please enter a number");

try {
    if(num != "" && num !== null && isFinite(+num)) {
        alert(Math.exp(num));
    } else {
        throw new TypeError("You have not entered a number.");
    }
} catch(e) {
    alert(e.name);
    alert(e.message);
    alert(e.stack); // non-standard property
}
```

 ***注意:**`Error`对象也支持一些非标准属性。使用最广泛的属性之一是:`stack`，它返回该错误的*堆栈跟踪*。您可以将它用于调试目的，但不要在生产站点上使用它。*****